# Generated by Django 3.1.2 on 2020-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('afname', models.CharField(max_length=100, null=True)),
                ('alname', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=5, null=True)),
                ('phoneno', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cfname', models.CharField(max_length=100, null=True)),
                ('clname', models.CharField(max_length=100, null=True)),
                ('cphone', models.CharField(max_length=100, null=True)),
                ('cemail', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('copyrightdate', models.DateField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem', models.IntegerField()),
            ],
            options={
                'db_table': 'movie_actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producerid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pfname', models.CharField(max_length=100, null=True)),
                ('plname', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'producer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('receiptno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('duedate', models.DateField(null=True)),
                ('salefname', models.CharField(max_length=100, null=True)),
                ('salelname', models.CharField(max_length=100, null=True)),
                ('paymentref', models.CharField(max_length=100, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem', models.IntegerField()),
                ('unitday', models.IntegerField(null=True)),
                ('unitprice', models.FloatField(null=True)),
                ('extendedprice', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'rent_line_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saleperson',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sfname', models.CharField(max_length=100, null=True)),
                ('slname', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'saleperson',
                'managed': False,
            },
        ),
    ]
