# Generated by Django 3.1.2 on 2020-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('afname', models.CharField(max_length=100, null=True)),
                ('alname', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=5, null=True)),
                ('phoneno', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
