# Generated by Django 3.1.2 on 2020-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100, null=True)),
                ('clname', models.CharField(max_length=100, null=True)),
                ('cphone', models.CharField(max_length=100, null=True)),
                ('cemail', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('copyrightdate', models.DateField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem', models.IntegerField()),
            ],
            options={
                'db_table': 'movie_actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('productid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pfname', models.CharField(max_length=100, null=True)),
                ('plname', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'producer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saleperson',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100, null=True)),
                ('slname', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'saleperson',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': False},
        ),
    ]
