# Generated by Django 3.1.2 on 2020-11-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201122_2148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actor',
        ),
    ]
